#!/bin/bash

### BEGIN INIT INFO
# Provides:				openerp-server-[NAME]
# Required-Start:		$syslog
# Required-Stop:		$syslog
# Should-Start:			$network
# Should-Stop:			$network
# Default-Start:		2 3 4 5
# Default-Stop:			0 1 6
# Short-Description:	OpenERP - Enterprise Resource Management software
# Description:			OpenERP is a complete ERP and CRM software.
### END INIT INFO

SERVERNAME=[NAME]
BASE_PATH=[PATH]

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DAEMON=${BASE_PATH}/bin/openerp-server-${SERVERNAME}
NAME=openerp-server-${SERVERNAME}
DESC=openerp-server-${SERVERNAME}
USER=[USER]
PIDDIR=/var/run/openerp
PIDFILE=${PIDDIR}/${SERVERNAME}/server.pid
CONFIGFILE=/etc/openerp/server/${SERVERNAME}.conf
DAEMON_OPTS="--config=$CONFIGFILE"

[ -x $DAEMON ] || exit 0
[ -f $CONFIGFILE ] || exit 0

if [ ! -d $PIDDIR/$SERVERNAME ]; then
	mkdir -p $PIDDIR/$SERVERNAME
	chown $USER:root -R $PIDDIR
fi

checkpid() {
	[ -f $PIDFILE ] || return 1
	pid=`cat $PIDFILE`
	[ -d /proc/$pid ] && return 0
	return 1
}

do_start() {
	start-stop-daemon --start --quiet --pidfile $PIDFILE \
		--chuid $USER  --background --exec $DAEMON -- $DAEMON_OPTS

	RETVAL=$?
	i=10
	max=1
	count=0
	while [ $i -gt 0 ]; do
		sleep 1
		i=$((i-=1))
		if [ ! -e $PIDFILE ]; then
			i=0
		elif [[ $count == $max ]]; then
			i=0
		else
			count=$((count+=1))
		fi
	done

	return $RETVAL
}

do_stop() {
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --oknodo

	RETVAL=$?
	i=10
	while [ $i -gt 0 ]; do
		sleep 1
		i=$((i-=1))
		if [ ! -e $PIDFILE ]; then
			i=0
		fi
	done
	rm -f $PIDFILE  # remove pidfile

	return $RETVAL
}

do_restart() {
	do_stop

	do_start

	return $RETVAL
}

start_daemon() {

	if [ -f $PIDFILE ]; then
		echo "pidfile already exists: $PIDFILE"
		exit 1
	fi

	echo -n "Starting $DESC: "

	do_start

	checkpid

	if [ $? -eq 1 ]; then                
		rm -f $PIDFILE
		echo "failed."
		exit 1
	fi

	echo "done."
}

stop_daemon() {

	checkpid

	if [ $? -eq 1 ]; then
		exit 0
	fi

	echo -n "Stopping $DESC: "

	do_stop

	if [ $? -eq 1 ]; then
		echo "failed."
		exit 1
	fi

	echo "done."
}

restart_daemon() {

	echo -n "Reloading $DESC: "

	do_restart

	checkpid

	if [ $? -eq 1 ]; then                
		rm -f $PIDFILE
		echo "failed."
		exit 1
	fi

	echo "done."
}

status_daemon() {

	echo -n "Checking $DESC: "

	checkpid

	if [ $? -eq 1 ]; then
		echo "stopped."
	else
		echo "running."
	fi
}

case "$1" in
	start) start_daemon ;;
	stop) stop_daemon ;;
	restart|force-reload) restart_daemon ;;
	status) status_daemon ;;
	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
		exit 1
		;;
esac

exit 0
