#!/bin/sh

### BEGIN INIT INFO
# Provides:		openerp-server-[NAME]
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Should-Start:		$network
# Should-Stop:		$network
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Enterprise Resource Management software
# Description:		OpenERP is a complete ERP and CRM software.
### END INIT INFO

SERVERNAME=[NAME]
BASE_PATH=[PATH]

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DAEMON=${BASE_PATH}/bin/openerp-server-${SERVERNAME}
NAME=openerp-server-${SERVERNAME}
DESC=openerp-server-${SERVERNAME}
USER=openerp
PIDFILE=/var/run/${NAME}.pid
OPTIONS="--config=/etc/openerp/server/${SERVERNAME}.conf"

test -x ${DAEMON} || exit 0

set -e

case "${1}" in
	start)
		echo -n "Starting ${DESC}: "

		start-stop-daemon --start --quiet --pidfile ${PIDFILE} \
			--chuid ${USER} --background --exec ${DAEMON} -- ${OPTIONS}

		echo "${NAME}."
		;;

	stop)
		echo -n "Stopping ${DESC}: "

		start-stop-daemon --stop --quiet --pidfile ${PIDFILE} \
			--oknodo

		echo "${NAME}."
		;;

	restart|force-reload)
		echo -n "Restarting ${DESC}: "
		do stop
		sleep 1
		do start

	*)
		N=/etc/init.d/${NAME}
		echo "Usage: ${NAME} {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
